### ISSUE TITLE
Opening large gist in browser crashes

### ISSUE THREAD

**Issue by The-Compiler** [k0shk0sh/FastHub#1273]
**FastHub Version:**  4.5.6
**Android Version:**  7.1.1 (SDK: 25)
**Device Information:**  
- MANUFACTURER: HMD Global
- BRAND: Nokia  
- MODEL: Nokia 8
---

Similar to #1161, opening a gist link in https://github.com/qutebrowser/qutebrowser/issues/3292#issuecomment-344796738 shows "No files" (a better error message would help here, IMHO).

However, touching the browser icon crashes:

```
FATAL EXCEPTION: main
Process: com.fastaccess.github, PID: 8749
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 941292 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3781)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.os.TransactionTooLargeException: data parcel size 941292 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3695)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3773)
	... 7 more
```

**Comment by k0shk0sh** [comment]
No files = no files loaded from the api and therefore that's called empty state I'm in no position to write different messages as its not me who wrote the api :p its either no files or there are files.

**Comment by The-Compiler** [comment]
I'm still seeing the same crash with 4.5.7.
