### ISSUE TITLE
Opening issue #448 on openhab/openhab.android crashes app

### ISSUE THREAD

**Issue by mueller-ma** [k0shk0sh/FastHub#1280]
**FastHub Version: 4.5.5**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer&Brand:** OnePlus  
- **Model:** OnePlus  X
---

Lineageos 14.2

**Comment by mueller-ma** [comment]
Ok, it crashes when I enable "dont load pictures on mobile". It doesnt matter if I'm on wifi or mobile.

**Comment by k0shk0sh** [comment]
Awesome, glad you find out the cause, I'll look into it.

**Comment by mueller-ma** [comment]
```
11-27 18:28:23.619 9585-9585/com.fastaccess.github.libre E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.fastaccess.github.libre, PID: 123
                                                                           java.lang.SecurityException: ConnectivityService: Neither user 1234 nor current process has android.permission.ACCESS_NETWORK_STATE.
                                                                               at android.os.Parcel.readException(Parcel.java:1684)
                                                                               at android.os.Parcel.readException(Parcel.java:1637)
                                                                               at android.net.IConnectivityManager$Stub$Proxy.getNetworkInfo(IConnectivityManager.java:1225)
                                                                               at android.net.ConnectivityManager.getNetworkInfo(ConnectivityManager.java:910)
                                                                               at com.fastaccess.helper.AppHelper.isDataPlan(AppHelper.java:190)
                                                                               at com.fastaccess.helper.PrefGetter.isAutoImageDisabled(PrefGetter.java:466)
                                                                               at com.fastaccess.provider.timeline.handler.DrawableHandler.handleTagNode(DrawableHandler.java:38)
                                                                               at net.nightwhistler.htmlspanner.HtmlSpanner.handleContent(HtmlSpanner.java:269)
                                                                               at net.nightwhistler.htmlspanner.HtmlSpanner.handleContent(HtmlSpanner.java:262)
                                                                               at net.nightwhistler.htmlspanner.HtmlSpanner.handleContent(HtmlSpanner.java:262)
                                                                               at net.nightwhistler.htmlspanner.HtmlSpanner.handleContent(HtmlSpanner.java:262)
                                                                               at net.nightwhistler.htmlspanner.HtmlSpanner.fromTagNode(HtmlSpanner.java:219)
                                                                               at net.nightwhistler.htmlspanner.HtmlSpanner.fromHtml(HtmlSpanner.java:174)
                                                                               at com.fastaccess.provider.timeline.HtmlHelper.htmlIntoTextView(HtmlHelper.java:48)
                                                                               at com.fastaccess.ui.adapter.viewholder.TimelineCommentsViewHolder.bind(TimelineCommentsViewHolder.java:185)
                                                                               at com.fastaccess.ui.adapter.IssuesTimelineAdapter.onBindView(IssuesTimelineAdapter.java:86)
                                                                               at com.fastaccess.ui.widgets.recyclerview.BaseRecyclerAdapter.onBindViewHolder(BaseRecyclerAdapter.java:88)
                                                                               at com.fastaccess.ui.widgets.recyclerview.BaseRecyclerAdapter.onBindViewHolder(BaseRecyclerAdapter.java:20)
                                                                               at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
                                                                               at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
                                                                               at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                                                                               at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                                                                               at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                                                                               at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                                                                               at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

It's the screenshot that causes the crash

**Comment by k0shk0sh** [comment]
https://github.com/openhab/openhab-android/issues/448
