### ISSUE TITLE
Fasthub keep crashing when purchasing pro

### ISSUE THREAD

**Issue by NobodyXu** [k0shk0sh/FastHub#2089]
I was trying to buy pro version of this app when it crahsed. I tried this several times and it just keeps happening.

**FastHub Version: 4.6.7** 
**Android Version: MIUI 10 8.10.11 Beta (Base on Android 7.1.1)**  
**Device Information:**  
- MANUFACTURER: Xiaomi
- BRAND: Xiaomi
- MODEL: MI MAX 2 
---

Log from my phone after crash:

```
io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onError(ObservableFlatMap.java:288)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:125)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:230)
	at rx_activity_result2.RxActivityResult$Builder$2.response(RxActivityResult.java:105)
	at rx_activity_result2.HolderActivity.onDestroy(HolderActivity.java:85)
	at android.app.Activity.performDestroy(Activity.java:7065)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4323)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4354)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6388)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
	at com.miguelbcr.io.rx_billing_service.RxBillingServiceImpl.processActivityResult(RxBillingServiceImpl.java:283)
	at com.miguelbcr.io.rx_billing_service.RxBillingServiceImpl.access$800(RxBillingServiceImpl.java:37)
	at com.miguelbcr.io.rx_billing_service.RxBillingServiceImpl$11$1$1.apply(RxBillingServiceImpl.java:259)
	at com.miguelbcr.io.rx_billing_service.RxBillingServiceImpl$11$1$1.apply(RxBillingServiceImpl.java:256)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
	... 16 more
``

**Comment by NobodyXu** [comment]
![screenshot_2018-11-01-17-56-15-479_com fastaccess github](https://user-images.githubusercontent.com/30436523/47837775-5d830000-de01-11e8-8d45-6a89ce1d4837.png)
A screenshot pf the crash.

**Comment by k0shk0sh** [comment]
Do you have google play services in your phone and playstore?

**Comment by NobodyXu** [comment]
Yes, I have both. I actually downloaded Fasthub from google play.

**Comment by yakov116** [comment]
@NobodyXu is this still an issue?
