### ISSUE TITLE
App crash on this isuue

### ISSUE THREAD

**Issue by vovpff** [k0shk0sh/FastHub#2872]
**FastHub Version: 4.7.3**  
**Android Version: 9 (SDK: 28)**  
**Device Information:**  
- **Manufacturer:** HUAWEI  
- **Brand:** HONOR  
- **Model:** Honor 10  
---

 When I scroll to bottom this issue https://github.com/YetiForceCompany/YetiForceCRM/issues/12567 looks like app crashed and restarted

**Comment by kj7rrv** [comment]
Confirmed, Moto g6; Android Pie

**Comment by kj7rrv** [comment]
It reloaded back to this issue, and now I do not see the original message and the Priority High label message is duplicated.

**Comment by maxakash** [comment]
Same issue on Asus Zenfone 5Z

**Comment by alyonatischenko** [comment]
@maxakash fuck yu lol

**Comment by alyonatischenko** [comment]
@alyonatischenko 
### 
## 
## 
### **
- **_~~:kissing_cl
osed_eyes:~~ _ ** **

**Comment by HitaloM** [comment]
Same issue on J7 2016 (One UI, Android 9)

**Comment by 3xploiton3** [comment]
No issue on me, redmi note 5, android 9

**Comment by naloder** [comment]
Same issue on Mi 8 lite(MIUI 11 20.1.21 Android Q )

**Comment by carlobrok** [comment]
Same issue, Huawei P20 lite Android 9.1

**Comment by Username404-59** [comment]
Same on oneplus 3T with android 9.

**Comment by timschneeb** [comment]
Also crashed on my Galaxy S8. Here is a stacktrace since no one bothered to paste one in here:
 
```
msg: java.lang.IndexOutOfBoundsException: setSpan (54 ... 53) has end before start
stacktrace: java.lang.IndexOutOfBoundsException: setSpan (54 ... 53) has end before start
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1318)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
	at com.fastaccess.provider.timeline.handler.QuoteHandler.handleTagNode(QuoteHandler.java:24)
	at net.nightwhistler.htmlspanner.HtmlSpanner.handleContent(HtmlSpanner.java:269)
	at net.nightwhistler.htmlspanner.HtmlSpanner.handleContent(HtmlSpanner.java:262)
	at net.nightwhistler.htmlspanner.HtmlSpanner.handleContent(HtmlSpanner.java:262)
	at net.nightwhistler.htmlspanner.HtmlSpanner.fromTagNode(HtmlSpanner.java:219)
	at net.nightwhistler.htmlspanner.HtmlSpanner.fromHtml(HtmlSpanner.java:174)
	at com.fastaccess.provider.timeline.HtmlHelper.htmlIntoTextView(HtmlHelper.java:48)
	at com.fastaccess.ui.adapter.viewholder.TimelineCommentsViewHolder.bind(TimelineCommentsViewHolder.java:197)
	at com.fastaccess.ui.adapter.IssuesTimelineAdapter.onBindView(IssuesTimelineAdapter.java:86)
	at com.fastaccess.ui.widgets.recyclerview.BaseRecyclerAdapter.onBindViewHolder(BaseRecyclerAdapter.java:88)
	at com.fastaccess.ui.widgets.recyclerview.BaseRecyclerAdapter.onBindViewHolder(BaseRecyclerAdapter.java:20)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
```
