### ISSUE TITLE
Repositories without files don't open anymore

### ISSUE THREAD

**Issue by StanNL** [k0shk0sh/FastHub#583]
**App Version: 2.5.3**

**OS Version: 25**

**Model: samsung-kminilte**

Here's an example, although the reason I specified in the title may not be the true cause:

[This repository](https://github.com/Spookcity/ROMS-G800F/)
   

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh toast issue

**Comment by k0shk0sh** [comment]
@yakov116 nope, it's definitely something else

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
```java
05-30 12:44:40.093 10703-12795/com.fastaccess.github D/OkHttp: Access-Control-Allow-Origin: *
05-30 12:44:40.094 10703-12795/com.fastaccess.github D/OkHttp: Content-Security-Policy: default-src 'none'
05-30 12:44:40.094 10703-12795/com.fastaccess.github D/OkHttp: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
05-30 12:44:40.094 10703-12795/com.fastaccess.github D/OkHttp: X-Content-Type-Options: nosniff
05-30 12:44:40.094 10703-12795/com.fastaccess.github D/OkHttp: X-Frame-Options: deny
05-30 12:44:40.094 10703-12795/com.fastaccess.github D/OkHttp: X-XSS-Protection: 1; mode=block
05-30 12:44:40.094 10703-12795/com.fastaccess.github D/OkHttp: Vary: Accept-Encoding
05-30 12:44:40.094 10703-12795/com.fastaccess.github D/OkHttp: X-Served-By: bae57931a6fe678a3dffe9be8e7819c8
05-30 12:44:40.095 10703-12795/com.fastaccess.github D/OkHttp: X-GitHub-Request-Id: E5C2:2E0FB:517FC1C:628E802:592DA178
05-30 12:44:40.095 10703-12795/com.fastaccess.github D/OkHttp: {"items":[]}
05-30 12:44:40.095 10703-12795/com.fastaccess.github D/OkHttp: <-- END HTTP (12-byte body)
05-30 12:44:40.173 10703-10703/com.fastaccess.github E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.fastaccess.github, PID: 10703
                                                                       android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@5ee9503 is not valid; is your activity running?
                                                                           at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
                                                                           at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
                                                                           at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                           at android.widget.Toast$TN.handleShow(Toast.java:434)
                                                                           at android.widget.Toast$TN$2.handleMessage(Toast.java:345)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
05-30 12:44:40.175 1517-2159/system_process W/ActivityManager:   Force finishing activity com.fastaccess.github/com.fastaccess.ui.modules.repos.RepoPagerActivity
05-30 12:44:40.191 1517-2159/system_process W/ActivityManager:   Force finishing activity com.fastaccess.github/com.fastaccess.ui.modules.repos.issues.issue.details.IssuePagerActivity
05-30 12:44:40.516 1238-1261/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
05-30 12:44:40.532 1517-4979/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
05-30 12:44:40.533 1517-4979/system_process D/OpenGLRenderer: Swap behavior 1
05-30 12:44:40.538 1238-1261/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
05-30 12:44:40.556 1238-1261/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
05-30 12:44:40.668 10703-10737/com.fastaccess.github I/CrashlyticsCore: Crashlytics report upload complete: 592D918201FE-0001-29CF-1819D0C1C9D4
05-30 12:44:40.700 1517-1531/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{60dbb0b u0 com.fastaccess.github/com.fastaccess.ui.modules.repos.RepoPagerActivity t68 f}
05-30 12:44:40.784 1517-4979/system_process E/EGL_emulation: tid 4979: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
05-30 12:44:40.784 1517-4979/system_process W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x911aa1a0, error=EGL_BAD_MATCH
05-30 12:44:43.597 1517-1517/system_process W/WindowManager: Attempted to remove non-existing token: android.os.Binder@4f4f6c4
05-30 12:44:45.948 2267-12804/com.google.android.gms W/PlatformStatsUtil: Could not retrieve Usage & Diagnostics setting. Giving up.
05-30 12:44:46.372 1517-1531/system_process W/ActivityManager: Launch timeout has expired, giving up wake lock!
05-30 12:44:46.945 1517-1527/system_process I/art: Background partial concurrent mark sweep GC freed 111899(3MB) AllocSpace objects, 5(228KB) LOS objects, 26% free, 11MB/15MB, paused 6.140ms total 67.109ms
05-30 12:44:50.214 1517-1531/system_process W/ActivityManager: Activity destroy timeout for ActivityRecord{d8627f7 u0 com.fastaccess.github/com.fastaccess.ui.modules.repos.issues.issue.details.IssuePagerActivity t68 f}
05-30 12:45:06.885 1517-1531/system_process W/ActivityManager: Timeout executing service: ServiceRecord{ce1edc7 u0 com.fastaccess.github/com.firebase.jobdispatcher.GooglePlayReceiver}
05-30 12:45:06.913 1517-1531/system_process I/ActivityManager: Crashing app skipping ANR: ProcessRecord{24d2753 10703:com.fastaccess.github/u0a73} executing service com.fastaccess.github/com.firebase.jobdispatcher.GooglePlayReceiver
05-30 12:47:49.681 1517-1527/system_process I/art: Background sticky concurrent mark sweep GC freed 55871(3MB) AllocSpace objects, 1(20KB) LOS objects, 24% free, 11MB/15MB, paused 6.876ms total 71.044ms
05-30 12:49:40.217 1517-2159/system_process W/ActivityManager:   Force finishing activity com.fastaccess.github/com.fastaccess.ui.modules.repos.RepoPagerActivity
05-30 12:49:40.278 1517-2159/system_process W/ActivityManager:   Force finishing activity com.fastaccess.github/com.fastaccess.ui.modules.repos.RepoPagerActivity
05-30 12:49:40.498 1517-2159/system_process W/ActivityManager:   Force finishing activity com.fastaccess.github/com.fastaccess.ui.modules.repos.issues.issue.details.IssuePagerActivity
05-30 12:49:40.608 1517-2159/system_process W/ActivityManager:   Force finishing activity com.fastaccess.github/com.fastaccess.ui.modules.repos.RepoPagerActivity
05-30 12:49:40.702 1517-2159/system_process W/ActivityManager:   Force finishing activity com.fastaccess.github/com.fastaccess.ui.modules.user.UserPagerActivity
05-30 12:49:40.810 1517-2159/system_process W/ActivityManager:   Force finishing activity com.fastaccess.github/com.fastaccess.ui.modules.main.MainActivity
05-30 12:49:40.936 1517-2159/system_process E/ActivityManager: Found activity ActivityRecord{57eafd u0 com.fastaccess.github/com.fastaccess.ui.modules.main.MainActivity t68 f} in proc activity list using null instead of expected ProcessRecord{24d2753 10703:com.fastaccess.github/u0a73}
05-30 12:49:40.987 1238-1753/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
05-30 12:49:41.029 1238-1753/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
05-30 12:49:41.072 1238-1753/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
05-30 12:49:41.144 1955-2090/com.google.android.googlequicksearchbox:search E/EGL_emulation: tid 2090: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
05-30 12:49:41.148 1955-2090/com.google.android.googlequicksearchbox:search W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x83f9eac0, error=EGL_BAD_MATCH
05-30 12:49:41.215 1517-2159/system_process I/ActivityManager: Killing 10703:com.fastaccess.github/u0a73 (adj 0): crash
05-30 12:49:41.217 1517-2159/system_process D/ActivityManager: cleanUpApplicationRecord -- 10703
05-30 12:49:41.235 1517-1531/system_process W/art: Long monitor contention with owner Binder:1517_B (2159) at void com.android.server.am.AppErrors.crashApplicationInner(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo)(AppErrors.java:372) waiters=0 in void com.android.server.am.ActivityManagerService$MainHandler.handleMessage(android.os.Message) for 880ms
05-30 12:49:41.237 1517-1538/system_process W/art: Long monitor contention with owner Binder:1517_B (2159) at void com.android.server.am.AppErrors.crashApplicationInner(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo)(AppErrors.java:372) waiters=1 in void com.android.server.am.ActivityRecord$Token.windowsGone() for 853ms
05-30 12:49:41.238 1517-1532/system_process W/art: Long monitor contention with owner Binder:1517_B (2159) at void com.android.server.am.AppErrors.crashApplicationInner(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo)(AppErrors.java:372) waiters=2 in void com.android.server.am.ActivityManagerService.unregisterReceiver(android.content.IIntentReceiver) for 813ms
05-30 12:49:41.239 1517-1532/system_process I/Choreographer: Skipped 60 frames!  The application may be doing too much work on its main thread.
05-30 12:49:41.246 1517-1538/system_process I/Choreographer: Skipped 51 frames!  The application may be doing too much work on its main thread.
05-30 12:49:41.375 1517-2158/system_process I/ActivityManager: Killing 8684:com.android.defcontainer/u0a5 (adj 906): empty for 11534s
05-30 12:49:41.395 1238-1269/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
```

**Comment by k0shk0sh** [comment]
@yakov116 it crashes because of your case only, the reason is

```
@Override public void onError(@NonNull Throwable throwable) {

int code = RestProvider.getErrorCode(throwable);

if (code == 404) {

sendToView(RepoPagerMvp.View::onFinishActivity);

} else {

onWorkOffline();

}

super.onError(throwable);
}
```


_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
GitHub returns 404 for the repo!

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by StanNL** [comment]
@k0shk0sh Hmm yeah I guess you're right. Maybe you could fetch the repo owner's list of repositories, and then check if this repo is in it.

_Sent from my Samsung kminilte using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@StanNL that will be too much to do since I'll have to fetch all and max paging size is 100 so I'll have to do some work, I guess I'll just ignore the 404 and keep it open. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
